update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "clean test")
  end

  desc "Deploy a new Internal Build to the Google Play"
  lane :internal do
    release
    upload_to_play_store(track: 'internal')
  end

  desc "Deploy a new version to the Firebase App Distribution"
  lane :distribute do
      release(assemble: true)
      firebase_app_distribution(
          app: "1:1093731557476:android:b7e8390b4cba7797b0ff71",
          service_credentials_file: CredentialsManager::AppfileConfig.try_fetch_value(:json_key_file),
          testers: "volkovskiyda@gmail.com"
      )
  end

  private_lane :release do |options|
      gradle(task: "clean")
      releaseTask = (options[:assemble] ? "assemble" : "bundle")
      gradle(
        task: releaseTask,
        build_type: "Release",
        print_command: false,
        properties: {
          "releaseStorePassword" => ENV["releaseStorePassword"],
          "releaseKeyAlias" => ENV["releaseKeyAlias"],
          "releaseKeyPassword" => ENV["releaseKeyPassword"],
          "apiKey" => ENV["apiKey"],
        }
      )
  end
end
