name: Fastlane

on:
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.2'
    - uses: maierj/fastlane-action@v2.0.1
      with:
        lane: 'distribute'
