name: Fastlane

on:
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7.2'
    - name: Service account
      env:
        serviceAccount: ${{ secrets.SERVICE_ACCOUNT }}
      run: echo $serviceAccount > movieapp-752e6-cd5df09c6569.json
    - uses: maierj/fastlane-action@v2.0.1
      env:
        releaseStorePassword: ${{ secrets.RELEASE_STORE_PASSWORD }}
        releaseKeyAlias: ${{ secrets.RELEASE_KEY_ALIAS }}
        releaseKeyPassword: ${{ secrets.RELEASE_KEY_PASSWORD }}
        apiKey: ${{ secrets.API_KEY }}
      with:
        lane: 'distribute'
